#test deploy5

spring:
  application:
    name: DDuBBukcho

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: 941227

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: true

jwt:
  secret: my-very-secret-key-for-jwt

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    groups-order: desc
    tags-sorter: alpha
    operationsSorter: method
  api-docs:
    path: /api/v3/api-docs
  paths-to-match:
    - /api/**

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: img-DDuBBukcho
      domain: https://img.DDuBBukcho.site

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/DDuBBukcho.log
  logback:
    rolling policy:
      max-history: 7
      max-file-size: 10MB